package com.example

import kotlinx.serialization.Serializable

@Serializable data class User(val name: String, val age: Int)

fun main() {
  // User.serializer() is generated by the kotlinx-serialization compiler plugin
  val serializer = User.serializer()
  println(serializer.descriptor)
}
